import Link from "next/link";
import { CaseStudyNav } from "./CaseStudyNav";

function SectionLabel({ number, children }: { number: string; children: string }) {
  return <p className="mb-6 text-[10px] font-medium uppercase tracking-[0.2em] text-stone-400">{number} / {children}</p>;
}

function Principle({ number, title, children }: { number: string; title: string; children: string }) {
  return <div className="border-t border-stone-200 py-7"><p className="font-mono text-xs text-stone-400">{number}</p><h3 className="mt-5 text-xl font-medium tracking-[-0.025em] text-stone-950">{title}</h3><p className="mt-3 text-sm leading-7 text-stone-500">{children}</p></div>;
}

export function CaseStudyPage() {
  return (
    <main className="bg-[#fafaf9] text-stone-900">
      <CaseStudyNav />
      <article className="mx-auto max-w-5xl px-6 lg:px-10">
        <header className="border-b border-stone-200 py-20 lg:py-28">
          <p className="mb-8 text-sm text-stone-400">产品设计过程 · 个人产品项目</p>
          <h1 className="text-5xl font-medium tracking-[-0.055em] text-stone-950 sm:text-7xl">FlowDay</h1>
          <p className="mt-5 text-2xl font-medium tracking-[-0.035em] text-stone-700 sm:text-3xl">计划时间，也记住生活。</p>
          <p className="mt-8 max-w-2xl text-lg leading-8 text-stone-600">从一个简单的日程工具，到连接「计划、行动与回顾」的 AI 时间管理与个人成长记录产品。</p>
          <div className="mt-12 grid max-w-3xl gap-7 border-t border-stone-200 pt-7 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-stone-400">项目类型</p><p className="mt-2 text-stone-700">个人产品项目</p></div><div><p className="text-xs text-stone-400">我的角色</p><p className="mt-2 text-stone-700">产品设计 / AI 产品设计 / Vibe Coding</p></div><div><p className="text-xs text-stone-400">项目阶段</p><p className="mt-2 text-stone-700">Interactive Prototype</p></div><div><p className="text-xs text-stone-400">核心工具</p><p className="mt-2 text-stone-700">Next.js · TypeScript · Tailwind CSS · Codex</p></div></div>
          <Link href="/app?demo=true" className="mt-10 inline-flex bg-stone-900 px-5 py-3 text-sm text-white transition-colors hover:bg-stone-700">体验产品 →</Link>
        </header>

        <section id="start" className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="01">起点</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">最开始，我只是想做一个日程本。</h2><div className="mt-10 max-w-2xl space-y-6 text-base leading-8 text-stone-600"><p>这个项目最初并没有复杂的 AI 构想。</p><p>最开始的目标很简单：做一个可以管理每天任务的个人日程工具。</p><p>第一版只有 Today、Tasks 和 Calendar。用户可以创建、完成、编辑和删除任务。</p><p>但随着产品逐渐可用，一个新的问题出现了。</p></div></section>

        <section id="evolution" className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="02">核心洞察</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">真正缺少的，<br />不是另一个 Todo 功能。</h2><div className="mt-10 max-w-2xl space-y-6 text-base leading-8 text-stone-600"><p>最初的 FlowDay 和大多数日程工具一样，关注的是：“接下来要做什么？”</p><p>但在实际使用过程中，我逐渐意识到：当一天、一周、一个月过去以后，任务列表很难回答另一个问题：“这段时间，我究竟是怎么度过的？”</p><p>完成的任务会从列表中消失，过去的计划也逐渐失去上下文。但真正构成一段生活的，不只有“完成了多少事情”，还有我把时间放在了哪里，有什么新的收获，哪些事情值得记住。</p><p>因此 FlowDay 的方向从任务管理逐渐转向：计划 → 行动 → 回顾。</p></div><div className="mt-14 grid gap-0 border-y border-stone-200 md:grid-cols-3">{[{ title: "计划", text: "我想怎么度过这段时间" }, { title: "行动", text: "我实际上做了什么" }, { title: "回顾", text: "我从中留下了什么" }].map((item, index) => <div key={item.title} className={`py-7 md:px-7 ${index > 0 ? "border-t border-stone-200 md:border-l md:border-t-0" : ""}`}><h3 className="text-2xl font-medium text-stone-950">{item.title}</h3><p className="mt-3 text-sm text-stone-500">{item.text}</p></div>)}</div><p className="mt-8 text-base text-stone-700">Calendar 记录时间。Tasks 记录行动。Reflection 记录成长。</p></section>

        <section className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="03">不同时间尺度</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">一天、一周、一个月和一年，不应该只是同一个页面的放大版。</h2><div className="mt-14 space-y-0 border-y border-stone-200">{[{ title: "每日", question: "今天发生了什么？", info: "具体任务 · 当天感受 · 收获 · 感谢" }, { title: "每周", question: "这一周我在推进什么？", info: "Weekly Plan · 实际任务 · 一周收获 · 下一周" }, { title: "每月", question: "我的时间和注意力去了哪里？", info: "方向 · 模式 · Moments · 变化" }, { title: "年度", question: "这一年有什么真正值得记住？", info: "月份 · 重要瞬间 · 变化 · 年度回望" }].map((item) => <div key={item.title} className="grid gap-3 border-b border-stone-200 py-6 last:border-b-0 sm:grid-cols-[100px_1fr_1fr] sm:gap-8"><h3 className="text-lg font-medium text-stone-950">{item.title}</h3><p className="text-sm text-stone-700">{item.question}</p><p className="text-sm leading-6 text-stone-400">{item.info}</p></div>)}</div><p className="mt-8 text-sm leading-7 text-stone-500">时间尺度越大，信息颗粒度应该越低。不要把全年几百条 Tasks 直接搬到 Yearly 页面。</p></section>

        <section id="ai" className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="04">AI 的问题</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">接入 AI 很容易。<br />让 AI 真正有意义，反而更难。</h2><div className="mt-10 max-w-2xl space-y-6 text-base leading-8 text-stone-600"><p>最初使用规则生成 Demo Summary，例如：“本周共记录 5 项任务，完成 2 项，主要集中在学习和个人生活。”</p><p>它虽然正确，但更像数据播报，并没有真正帮助用户理解这一周。</p><p>因此我重新定义 AI 的角色：不是总结任务，而是帮助用户重新看见自己已经留下的记录。</p></div></section>

        <section className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="05">AI 上下文架构</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">AI 不需要一次读完我的整个人生。</h2><div className="mt-14 grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div className="space-y-4 border-y border-stone-200 py-7 text-sm text-stone-700"><p>任务 + 每日记录</p><p className="pl-6 text-stone-400">↓ 每日整理</p><p>每周回顾</p><p className="pl-6 text-stone-400">↓ 每月回顾</p><p>年度回望</p></div><div className="space-y-7 text-sm leading-7 text-stone-500"><p>年度 AI 不直接读取全年几百条 Tasks 和几百篇 Daily Reflection，而是优先读取 Monthly Plans、Monthly Reflections、Monthly AI Summaries、重要瞬间和 Yearly Reflection。</p><p>这样可以减少上下文噪声，保留不同时间尺度真正重要的信息，也让 Daily、Weekly、Monthly、Yearly 拥有不同的 AI 角色。</p><p className="text-stone-700">AI Context 本身也是产品设计的一部分。</p></div></div></section>

        <section className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="06">AI 产品原则</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">我不希望 FlowDay<br />变成另一个“效率监督者”。</h2><div className="mt-14 grid gap-0 md:grid-cols-2"><Principle number="01" title="不为生活打分">不设计 Productivity Score。</Principle><Principle number="02" title="不制造焦虑">Overdue 只是时间状态，不是失败警告。</Principle><Principle number="03" title="没有记录，就不编造">AI 不推断用户没有写下的经历或情绪。</Principle><Principle number="04" title="不替用户定义意义">AI 可以帮助发现模式，但最终什么值得记住，由用户决定。</Principle><Principle number="05" title="计划不是 KPI">计划是方向，不是用来证明一个人是否足够努力。</Principle></div></section>

        <section id="demo" className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="07">体验设计</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">让第一次使用，<br />不必从一张空白页面开始。</h2><div className="mt-10 max-w-2xl space-y-6 text-base leading-8 text-stone-600"><p>FlowDay 的很多价值只有在积累了一段时间的数据后，才会真正出现。</p><p>每周回顾需要过去几天的任务与记录，每月回顾需要几周的数据，年度页面则需要更长时间尺度的积累。</p><p>如果第一次进入产品只看到“暂无任务”，用户很难立即理解这些功能之间是如何连接起来的。</p><p>因此我设计了示例体验模式。</p></div><div className="mt-12 grid gap-8 border-y border-stone-200 py-8 text-sm sm:grid-cols-2"><div><p className="text-xs text-stone-400">虚构 Persona</p><p className="mt-3 text-lg text-stone-800">林然</p><p className="mt-1 text-stone-500">24 岁 · 产品设计师</p></div><div><p className="text-xs text-stone-400">示例数据覆盖</p><p className="mt-3 leading-7 text-stone-600">过去约 30 天<br />今天<br />未来约 7 天</p></div></div><p className="mt-8 max-w-2xl text-sm leading-7 text-stone-500">示例数据包括任务、每日记录、每周计划与回顾、月度记录、年度聚合和 AI 示例回顾。日期根据访问当天动态生成，因此示例体验始终处在“现在”，而不是停留在某个固定日期。</p></section>

        <section className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="08">原型范围</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">我刻意没有做什么。</h2><div className="mt-10 max-w-2xl space-y-6 text-base leading-8 text-stone-600"><p>这一轮没有加入社交、打卡、番茄钟、效率评分、复杂通知或大量数据 Dashboard。</p><p>这些功能可以增加产品复杂度，但并不会强化 FlowDay 当前最核心的问题：计划、行动、回顾。</p><p>真实 OpenAI Server API 架构已经完成，但公开 Portfolio Demo 默认使用本地示例 AI Reflection，避免 API 成本、Demo 不稳定和 Key 暴露。</p><p>这是 Prototype Scope Decision，而不是未完成事项。</p></div></section>

        <section className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="09">技术与 Vibe Coding</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">从产品想法，<br />到可以真正点击的原型。</h2><div className="mt-12 grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div className="text-sm leading-8 text-stone-600">Next.js<br />TypeScript<br />Tailwind CSS<br />LocalStorage<br />OpenAI-ready 服务端 API</div><div className="space-y-6 text-sm leading-7 text-stone-500"><p>开发方式：Vibe Coding。</p><p>我负责产品问题定义、信息架构、功能优先级、交互决策、AI Context Design、Prompt Direction、QA 与迭代。</p><p>Codex 用于实现代码、重构、Debug、类型检查和 Build Validation。</p><p>Vibe Coding 并没有减少产品判断的重要性，反而要求更清楚地描述做什么、为什么做、什么暂时不做，以及如何验收。</p></div></div></section>

        <section id="learning" className="border-b border-stone-200 py-20 lg:py-28"><SectionLabel number="10">我学到了什么</SectionLabel><h2 className="max-w-2xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">这个项目让我重新理解了<br />“做一个 AI 产品”。</h2><div className="mt-14 grid gap-x-10 gap-y-0 md:grid-cols-2"><Principle number="01" title="功能不是越多越完整。">产品需要一个清楚的核心问题。</Principle><Principle number="02" title="AI 不是一个按钮。">Context、触发时机、输入数据和输出形式共同决定 AI 是否真正有价值。</Principle><Principle number="03" title="Prototype 也需要真实使用。">产品中的设计都来自实际使用后的问题，而不是最初 PRD。</Principle><Principle number="04" title="Vibe Coding 的瓶颈并不总是代码能力。">更常见的是需求是否清楚、边界是否明确，以及能否持续做出产品判断。</Principle></div></section>

        <section className="py-24 lg:py-32"><h2 className="max-w-3xl text-4xl font-medium leading-[1.15] tracking-[-0.045em] text-stone-950 sm:text-5xl">FlowDay 仍然是一个原型。<br /><span className="text-stone-400">但它已经让我回答了最开始没有想到的问题：</span></h2><p className="mt-10 max-w-2xl text-xl leading-9 text-stone-700">一个时间管理产品，除了告诉我们下一步做什么，<br />还能不能帮助我们记住自己是怎么走到这里的？</p><div className="mt-12 flex flex-wrap gap-5"><Link href="/app?demo=true" className="bg-stone-900 px-5 py-3 text-sm text-white transition-colors hover:bg-stone-700">体验 FlowDay →</Link><Link href="/" className="px-0 py-3 text-sm text-stone-500 hover:text-stone-900">返回作品集首页 →</Link></div></section>
      </article>
    </main>
  );
}
